---
- name: Install apt repo
  apt_repository: repo='deb [arch=amd64] http://mirrors.ripple.com/ubuntu/ trusty stable contrib'
- name: Install apt repo key
  apt_key: url=http://mirrors.ripple.com/mirrors.ripple.com.gpg.key

- name: Install rippled
  apt: update_cache=true name=rippled state={{rippled_package_state}}
- name: Make rippled data directories
  file: state=directory owner=rippled group=rippled path={{rippled_database_path}}

- name: Configure rippled
  template: src={{rippled_config_template}} dest=/etc/rippled/rippled.cfg

- name: Make rippled certs directories
  file: state=directory owner=rippled group=rippled path=/etc/rippled/certs
  when: rippled_ssl_cert or rippled_ssl_chain or rippled_ssl_key
- name: Add ssl cert
  copy: src={{rippled_ssl_cert}} dest=/etc/rippled/certs/rippled.crt owner=rippled group=rippled mode="u=rw,g=r,o=r"
  when: rippled_ssl_cert
- name: Add ssl chain cert
  copy: src={{rippled_ssl_chain}} dest=/etc/rippled/certs/rippled.crt owner=rippled group=rippled mode="u=rw,g=r,o=r"
  when: rippled_ssl_chain
- name: Add ssl key
  copy: src={{rippled_ssl_key}} dest=/etc/rippled/certs/rippled.key owner=rippled group=rippled mode="u=rw,g=r,o=r"
  when: rippled_ssl_key

- name: Stop rippled
  service: name=rippled state=stopped
  ignore_errors: true
  when: rippled_run_service == true
- name: Wait for rippled to become available
  wait_for: state=drained port=51234
  when: rippled_run_service == true
- name: Start rippled
  command: service rippled start
  when: rippled_run_service == true
- name: Wait for rippled to become available
  wait_for: port=51234
  when: rippled_run_service == true
